### ISSUE TITLE
I lose my temper

### ISSUE THREAD

**Issue by AliceRixte** [youqad/Coherence-of-Heyting-arithmetic#5]
well not really but this is really annoying when you spend 5 hours to do, undo and redo the same proof.
Do you have any clue on the "admits"?

**Comment by youqad** [comment]
I know right... I can relate to that (for some of the proofs, I spent hours and hours on them, and for others, it was almost immediate when you see how to broach the proof with the right angle) 😞

Unfortunately, I have no clue about any of the remaining admitted parts right now: I have a lot of neuroscience-related work, so I haven't had much time to think about it either (although I've spent several unsuccessful hours on the proof Farzad has just tackled).
It's really a matter of using the right sublemmas (some trivialize the proof, while with others, it's a nightmare). But somehow, I really feel like we should begin to use all the `flift_i`, `fsubst_i`, `cformula_i`, ... lemmas (otherwise what's the point of requiring to prove them?)

**Comment by AliceRixte** [comment]
I thought they were for the proof before this one. I'll try again tomorrow.

**Comment by youqad** [comment]
@141592653 I've already used the `tlift_i`, `tsubst_i` and `cterm_i` lemmas to prove the `flift_i`, `fsubst_i` and `cformula_i` ones, but the latter haven't been used yet. Same thing for the `tinterp_i` lemmas: they have to be used somewhere at some point.

**Comment by AliceRixte** [comment]
I made a breakthrough ! I had to use soundness rules and it was near from trivial... :'(

**Comment by youqad** [comment]
Congrats! 🎉 Farzad and you have written quite a lot of things during the past few days: I'll try to catch up with what you did as soon as possible 😄
